"""
Comprehensive tests for Fractional Factorial Design.

Testing Strategy for Fractional Factorial:
-----------------------------------------
Unlike Full Factorial where we can verify exact matrices, Fractional Factorial
designs are generated by the doe_box library with specific mathematical properties.
We test PROPERTIES, not exact values:

1. Run count formula: 2^(k-p) where k=factors, p=fraction
2. All coded values must be -1 or +1 (2-level design)
3. Resolution properties (what's aliased and what's not)
4. Orthogonality of main effects
5. Balance (equal -1 and +1 counts per factor)
6. Fraction reduction (fewer runs than full factorial)
"""

import itertools
import numpy as np
import pytest
from doetools.design.process import FractionalFactorialDesign
from doetools.utils import ContinuousFactor
from doetools import ModelTerms


class TestFractionalFactorialInitialization:
    """Test initialization and input validation"""
    
    def test_valid_initialization(self):
        """Test that valid inputs create a design"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        assert design is not None
        assert design._design_type == "Fractional Factorial"
        assert design._resolution == 3
    
    def test_too_many_factors(self): 
        """Test that more than 26 factors raise error"""
        factors = {
            f'X{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, 28)  # 27 factors
        }
        
        with pytest.raises(ValueError, match="Cannot handle more than 26 factors"):
            FractionalFactorialDesign(factors=factors, resolution=3)
    
    def test_invalid_center_points(self):
        """Test that negative center points raise error"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        with pytest.raises(ValueError, match="Center points must be a non-negative integer"):
            FractionalFactorialDesign(factors=factors, resolution=3, center_points=-1)
    
    def test_invalid_replicates(self):
        """Test that negative replicates raise error"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        with pytest.raises(ValueError, match="Replicates must be a non-negative integer"):
            FractionalFactorialDesign(factors=factors, resolution=3, replicates=-1)
    
    def test_non_two_level_factors(self):
        """Test that factors with non-2 levels raise error"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=3, lower_bound=0, upper_bound=10, decimals=1)  # 3 levels
        }
        
        with pytest.raises(ValueError, match="only supports 2-level factors"):
            FractionalFactorialDesign(factors=factors, resolution=3)


class TestFractionalFactorialProperties:
    """Test fundamental properties of fractional factorial designs"""
    
    def test_run_count_formula_4_factors_res_4(self):
        """Test 2^(4-1) = 8 runs for 4 factors at resolution IV"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X4': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        
        # 2^(4-1) = 2^3 = 8 runs (half-fraction)
        assert len(design._coded_design_matrix) == 8
    
    def test_run_count_formula_5_factors_res_3(self):
        """Test 2^(5-2) = 8 runs for 5 factors at resolution III"""
        factors = {
            f'X{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, 6)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # 2^(5-2) = 2^3 = 8 runs (quarter-fraction)
        assert len(design._coded_design_matrix) == 8
    
    def test_run_count_formula_7_factors_res_4(self):
        """Test 2^(7-3) = 16 runs for 7 factors at resolution IV"""
        factors = {
            f'X{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, 8)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        
        # 2^(7-3) = 2^4 = 16 runs
        assert len(design._coded_design_matrix) == 16
    
    def test_coded_values_are_two_level(self):
        """Test that all coded values are exactly -1 or +1"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X4': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        
        # Exclude center points if any (they would be 0)
        for col in design._coded_design_matrix.columns:
            unique_vals = design._coded_design_matrix[col].unique()
            # Should only contain -1, 1 (and possibly 0 for center points)
            assert all(v in [-1, 1] for v in unique_vals)
            
    def test_uncoded_values_are_two_level(self):
        """Test that all coded values are exactly -1 or +1"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X4': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        
        # Exclude center points if any (they would be 0)
        for col in design._design_matrix.columns:
            unique_vals = design._design_matrix[col].unique()
            # Should only contain -1, 1 (and possibly 0 for center points)
            assert all(v in [0, 10] for v in unique_vals)
    
    def test_fewer_runs_than_full_factorial(self):
        """Test that fractional factorial has fewer runs than full factorial"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X4': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X5': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Fractional should have < 2^5 = 32 runs
        full_factorial_runs = 2 ** len(factors)
        assert len(design._coded_design_matrix) < full_factorial_runs
    
    def test_design_dimensions(self):
        """Test that design matrix has correct shape"""
        factors = {
            'Temp': ContinuousFactor(n_levels=2, lower_bound=20, upper_bound=80, decimals=1),
            'Pressure': ContinuousFactor(n_levels=2, lower_bound=1, upper_bound=5, decimals=1),
            'Time': ContinuousFactor(n_levels=2, lower_bound=10, upper_bound=60, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Should have 3 columns (one per factor)
        assert design._coded_design_matrix.shape[1] == 3
        assert list(design._coded_design_matrix.columns) == ['Temp', 'Pressure', 'Time']
    
    @pytest.mark.parametrize("num_factors,resolution", [
        (4, 4),
        (4, 3),
        (5, 3),
        (5, 4),
        (6, 4),
        (6, 3),
        (7, 4),
        (7, 3),
        (7, 5),
        (8, 5)
    ])
    def test_balance_property(self, num_factors, resolution):
        """Test that each factor has balanced -1 and +1 counts"""
        
        factors = {f"X{i}": ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
                   for i in range(1, num_factors + 1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=resolution)
        
        # Each factor should have equal counts of -1 and +1 (excluding center points)
        for col in design._coded_design_matrix.columns:
            
            count_low = (design._coded_design_matrix[col] == -1).sum()
            count_high = (design._coded_design_matrix[col] == 1).sum()
            
            # Balanced Design: counts should be equal
            assert abs(count_low - count_high) == 0


class TestFractionalFactorialOrthogonality:
    """Test orthogonality properties of fractional factorial designs"""
    
    @pytest.mark.parametrize("num_factors, resolution", [(4, 3), (5, 3), (5,4), (6, 3), (6, 4), (7, 4)])
    def test_main_effects_orthogonality(self, num_factors, resolution):
        """Test that main effects are orthogonal for Resolution III design"""
        factors = {f"X{i}": ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
                   for i in range(1, num_factors + 1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=resolution)
        
        # Calculate correlations between main effects
        coded = design._coded_design_matrix
        for i, col1 in enumerate(coded.columns):
            for col2 in coded.columns[i+1:]:
                correlation = coded[col1].dot(coded[col2])
                # Main effects should be orthogonal (correlation = 0)
                assert abs(correlation) < 1e-10, \
                    f"Main effects {col1} and {col2} not orthogonal: correlation = {correlation}"


class TestFractionalFactorialFeatures:
    """Test additional features like center points and replicates"""
    
    def test_center_points_added(self):
        """Test that center points are added correctly"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3, center_points=4)
        
        # Should have base runs + 4 center points
        base_runs = 4  # 2^(3-1) = 4 for resolution III
        assert len(design._coded_design_matrix) == base_runs + 4
        
        # Center points should have all zeros in coded matrix
        center_rows = design._coded_design_matrix.tail(4)
        assert (center_rows == 0).all().all()
    
    def test_replicates_multiplies_runs(self):
        """Test that replicates multiply the number of design points"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design_no_rep = FractionalFactorialDesign(factors=factors, resolution=3)
        design_with_rep = FractionalFactorialDesign(factors=factors, resolution=3, replicates=2)
        
        # With 2 replicates, should have 3x the runs (original + 2 replicates)
        assert len(design_with_rep._coded_design_matrix) == len(design_no_rep._coded_design_matrix) * 3
    
    def test_center_points_and_replicates_combined(self):
        """Test combining center points and replicates"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(
            factors=factors,
            resolution=3,
            center_points=3,
            replicates=1
        )
        
        # Base runs = 4 (2^(3-1))
        # With 1 replicate: 4 * 2 = 8
        # Plus 3 center points = 11 total
        assert len(design._coded_design_matrix) == 11


class TestFractionalFactorialDecoding:
    """Test decoding from coded to actual values"""
    
    def test_decoded_values_at_bounds(self):
        """Test that decoded values are at factor low/high bounds"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=10, upper_bound=50, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=100, upper_bound=200, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=1, upper_bound=5, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Coded -1 should map to lower bound, +1 to upper bound (no center points)
        for _, row in design._design_matrix.iterrows():
            assert row['X1'] in [10.0, 50.0]  # low or high (no center)
            assert row['X2'] in [100.0, 200.0]
            assert row['X3'] in [1.0, 5.0]
    
    def test_decoded_center_points(self):
        """Test that center points decode to midpoint of factor ranges"""
        factors = {
            'Temp': ContinuousFactor(n_levels=2, lower_bound=20, upper_bound=80, decimals=1),
            'Pressure': ContinuousFactor(n_levels=2, lower_bound=1, upper_bound=5, decimals=1),
            'Time': ContinuousFactor(n_levels=2, lower_bound=10, upper_bound=30, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3, center_points=3)
        
        # Last 3 rows should be center points
        center_rows = design._design_matrix.tail(3)
        
        # Center should be midpoint of range
        assert all(center_rows['Temp'] == 50.0)  # (20 + 80) / 2
        assert all(center_rows['Pressure'] == 3.0)  # (1 + 5) / 2
        assert all(center_rows['Time'] == 20.0)  # (10 + 30) / 2


class TestFractionalFactorialSpecificDesigns:
    """Test specific well-known fractional factorial designs"""
    
    def test_2_4_1_design(self):
        """Test 2^(4-1) design (4 factors, 8 runs, Resolution IV)"""
        factors = {
            'A': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'B': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'C': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'D': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        
        # Properties of 2^(4-1) Resolution IV:
        assert len(design._coded_design_matrix) == 8  # 2^3 runs
        assert design._coded_design_matrix.shape[1] == 4  # 4 factors
        
        # All values should be ±1
        for col in design._coded_design_matrix.columns:
            assert set(design._coded_design_matrix[col].unique()) == {-1, 1}
    
    def test_2_5_2_design(self):
        """Test 2^(5-2) design (5 factors, 8 runs, Resolution III)"""
        factors = {
            f'Factor{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, 6)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Properties of 2^(5-2) Resolution III:
        assert len(design._coded_design_matrix) == 8  # 2^3 runs
        assert design._coded_design_matrix.shape[1] == 5  # 5 factors
    
    def test_2_6_3_design(self):
        """Test 2^(6-3) design (6 factors, 8 runs, Resolution III)"""
        factors = {
            f'X{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, 7)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Properties of 2^(6-3) Resolution III:
        assert len(design._coded_design_matrix) == 8  # 2^3 runs
        assert design._coded_design_matrix.shape[1] == 6  # 6 factors
        
        # Check balance for each factor
        for col in design._coded_design_matrix.columns:
            assert (design._coded_design_matrix[col] == -1).sum() == 4
            assert (design._coded_design_matrix[col] == 1).sum() == 4


class TestFractionalFactorialAliasStructure:
    
    """Test alias structure detection"""
    
    def test_alias_check_requires_model_matrix(self):
        """Test that alias_check requires model matrix to be computed first"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Should raise error if no model matrix exists
        with pytest.raises(ValueError, match="No model matrix defined"):
            design.alias_check()
    
    "Check that RES III design has no main effect aliasing"
    
    @pytest.mark.parametrize("num_factors", [4, 5, 6, 7, 8])
    def test_no_main_effect_aliasing_resolution_3(self, num_factors):
        
        """Test that Resolution III designs have no main effect aliasing"""
        
        factors = {f"X{i}": ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
                        for i in range(num_factors)}
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        coded = design._coded_design_matrix
        tol = 1e-8
        # Check orthogonality between first num_factors columns (real factors)
        for i in range(num_factors):
            for j in range(i + 1, num_factors):
                dot_product = np.dot(coded.iloc[:, i].values, coded.iloc[:, j].values)
                assert abs(dot_product) <= 0 + tol, f"Factors {i} and {j} not orthogonal: dot={dot_product}"

    "Check that RES IV design has no main effect or 2-factor interaction aliasing"
    
    @pytest.mark.parametrize("num_factors, num_int2", [(4, 2), (5, 5), (6, 5), (7, 5), (8, 5)])
    def test_no_main_effect_2fi_aliasing_resolution_4(self, num_factors, num_int2):
        """Test that Resolution IV designs have no main effect or 2-factor interaction aliasing"""
        
        factors = {f"X{i}": ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
                        for i in range(num_factors)}
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        coded = design._coded_design_matrix
        int2 = list(itertools.combinations(coded.columns, 2))[:num_int2] # Get the first num_int2 factor interactions
        model_terms = ModelTerms(intercept=True, pro_main="all", pro_int2=int2, pro_quadratic=None)
        design.set_model_terms(model_terms)
        tol = 1e-8
        
        # Check orthogonality between first num_factors columns - Main effects
        for i in range(num_factors):
            for j in range(i + 1, num_factors):
                dot_product = np.dot(coded.iloc[:, i].values, coded.iloc[:, j].values)
                assert abs(dot_product) <= 0 + tol, f"Factors {i} and {j} not orthogonal: dot={dot_product}"
        
        # Extract 2-factor interactions (columns after intercept and main effects)
        # Model matrix structure: [intercept, main_effects, 2FI]
        # Skip first (1 + num_factors) columns to get 2FI
        two_factor_interactions = design._model_matrix.iloc[:, (1 + num_factors):]
        
        # Check orthogonality between main effects and 2-factor interactions
        for i in range(num_factors):
            for j in range(two_factor_interactions.shape[1]):
                dot_product = np.dot(coded.iloc[:, i].values, two_factor_interactions.iloc[:, j].values)
                assert abs(dot_product) <= 0 + tol, f"Main effect {i} and 2-FI {j} not orthogonal: dot={dot_product}"

    "Check that RES V design has no 2-factor interaction aliasing with other 2-factor interactions"
    @pytest.mark.parametrize("num_factors", [5, 6, 7, 8])
    def test_no_2fi_2fi_aliasing_resolution_5(self, num_factors):
        """Test that Resolution V designs have no 2FI-2FI aliasing"""
        
        factors = {f"X{i}": ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
                        for i in range(num_factors)}
        
        design = FractionalFactorialDesign(factors=factors, resolution=5)
        model_terms = ModelTerms(intercept=True, pro_main="all", pro_int2="all", pro_quadratic=None)
        design.set_model_terms(model_terms)
        tol = 1e-8
        
        # Extract 2-factor interactions (columns after intercept and main effects)
        # Model matrix structure: [intercept, main_effects, 2FI]
        two_factor_interactions = design._model_matrix.iloc[:, (1 + num_factors):]
        
        # Check orthogonality between all pairs of 2-factor interactions
        for i in range(two_factor_interactions.shape[1]):
            for j in range(i + 1, two_factor_interactions.shape[1]):
                dot_product = np.dot(two_factor_interactions.iloc[:, i].values, 
                                   two_factor_interactions.iloc[:, j].values)
                assert abs(dot_product) <= 0 + tol, \
                    f"2-FI {i} and 2-FI {j} not orthogonal: dot={dot_product}"
                        
class TestFractionalFactorialEdgeCases:
    """Test edge cases and boundary conditions"""
    
    def test_three_factors_minimum(self):
        """Test design with minimum 3 factors"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        assert len(design._coded_design_matrix) == 4  # 2^(3-1) = 4
        assert design._coded_design_matrix.shape[1] == 3
    
    def test_many_factors(self):
        """Test design with many factors (10 factors)"""
        factors = {
            f'Factor_{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, 11)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        
        # Should successfully create design
        assert design._coded_design_matrix.shape[1] == 10
        assert len(design._coded_design_matrix) > 0
        
        # Should have fewer runs than 2^10 = 1024
        assert len(design._coded_design_matrix) < 1024
    
    def test_zero_center_points_zero_replicates(self):
        """Test default behavior with no center points or replicates"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Should have only base design points (no center, no replicates)
        assert len(design._coded_design_matrix) == 4  # 2^(3-1) = 4
        
        # No rows should be all zeros (no center points)
        all_zero_rows = (design._coded_design_matrix == 0).all(axis=1).sum()
        assert all_zero_rows == 0
    
    def test_large_number_of_center_points(self):
        """Test design with many center points"""
        factors = {
            'X1': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X2': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'X3': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=3, center_points=10)
        
        # For 3 factors at resolution 3: 2^(3-1) = 4 base runs
        # Should have 4 base runs + 10 center points = 14 total
        assert len(design._coded_design_matrix) == 14
        
        # Last 10 rows should be all zeros (center points)
        center_rows = design._coded_design_matrix.tail(10)
        assert (center_rows == 0).all().all()


class TestFractionalFactorialResolutionDifferences:
    """Test differences between resolution levels"""
    
    @pytest.mark.parametrize("num_factors", [4, 5, 6, 7, 8])
    def test_resolution_3_vs_4_run_counts(self, num_factors):
        """Test that Resolution III uses fewer runs than Resolution IV for same factors"""
        factors = {
            f'X{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, num_factors + 1)  
        }
        
        design_res3 = FractionalFactorialDesign(factors=factors, resolution=3)
        design_res4 = FractionalFactorialDesign(factors=factors, resolution=4)
        
        # Higher resolution needs more runs
        # Resolution III: more aggressive fraction
        # Resolution IV: less aggressive fraction (needs more runs)
        assert len(design_res4._coded_design_matrix) >= len(design_res3._coded_design_matrix)
    
    def test_resolution_affects_fraction_size(self):
        """Test that resolution controls the degree of fractionation"""
        factors = {
            f'X{i}': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
            for i in range(1, 6)  # 5 factors
        }
        
        design_res3 = FractionalFactorialDesign(factors=factors, resolution=3)
        design_res5 = FractionalFactorialDesign(factors=factors, resolution=5)
        
        # Resolution V should use more runs (less fractionation)
        assert len(design_res5._coded_design_matrix) >= len(design_res3._coded_design_matrix)
        
        # Both should be less than full factorial (2^5 = 32)
        assert len(design_res3._coded_design_matrix) <= 32
        assert len(design_res5._coded_design_matrix) <= 32
    
class TestAliasStructureCheck:
    """Test alias structure checking functionality"""
    
    def test_alias_structure_detection_no_alias(self):
        """Test that no aliases are detected in well-designed Resolution IV design"""
        factors = {
            'A': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'B': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'C': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'D': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        design = FractionalFactorialDesign(factors=factors, resolution=4)
        int2 = list(itertools.combinations(factors.keys(), 2))[:3]  # First 3 two-factor interactions
        model_terms = ModelTerms(intercept=True, pro_main="all", pro_int2=int2, pro_quadratic=None)
        design.set_model_terms(model_terms)
        
        design.alias_check()
        
        # In a 2^(4-1) Resolution IV design, main effects should not be aliased with 2FI
        assert len(design._aliases) == 0
    
    def test_alias_structure_detection_alias(self):
        """Test that aliases are detected in Resolution III design with 2FI"""
        factors = {
            'A': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'B': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'C': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'D': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1),
            'E': ContinuousFactor(n_levels=2, lower_bound=0, upper_bound=10, decimals=1)
        }
        
        # 2^(5-2) Resolution III design: 8 runs, 5 factors
        design = FractionalFactorialDesign(factors=factors, resolution=3)
        
        # Test each 2FI individually to see which ones are aliased
        all_2fi = list(itertools.combinations(factors.keys(), 2))
        aliases_found = False
        
        for int2 in all_2fi:
            # Test with just main effects and this one 2FI
            # Model: 1 intercept + 5 main + 1 2FI = 7 terms (< 8 runs, not saturated)
            model_terms = ModelTerms(intercept=True, pro_main="all", pro_int2=[int2], pro_quadratic=None)
            design.set_model_terms(model_terms)
            design.alias_check()
            
            if len(design._aliases) > 0:
                aliases_found = True
                break
        
        # In Resolution III, at least some 2FI must be aliased with main effects
        assert aliases_found, "No aliases detected in Resolution III design with 2FI"
    
