# Import necessary libraries
import numpy as np
 
# Import mixins and core abstract design class 
from ...utils import Design
from ...graphs import GraphsMixin
from ...utils import FileUploaderMixin
from ...utils import ParetoMixin
from ...utils import ContinuousFactor, CategoricalFactor

# Class Definition
class ImportDesign(Design, GraphsMixin, FileUploaderMixin, ParetoMixin):
  """
  Import and validate experimental designs from external files.

  This class allows users to import existing experimental designs from CSV or
  Excel files, automatically infers factor properties, and validates the design
  structure. Useful for analyzing previously conducted experiments or designs
  generated by other software.

  Parameters:
    vars : list of str
        List of variable (factor) names to extract from the file. Must match
        column names in the imported file.
    vars_type : list of str
        List of variable types corresponding to each factor in `vars`.
        Valid values are 'cont' (continuous) or 'cat' (categorical).
        Length must match `vars`.
    file_path : str
        Path to the file containing the experimental design. Supports CSV
        (.csv) and Excel (.xlsx, .xls) formats.
    coded : bool, optional
        If True, assumes the imported data is already in coded form (-1, 0, 1, etc.).
        If False (default), treats data as actual factor levels and generates
        coded values automatically.

  Raises:
    ValueError: If `vars_type` length does not match `vars` length.
    ValueError: If any variable type in `vars_type` is not 'cont' or 'cat'.
    ValueError: If any variable name in `vars` is not found in the file columns.

  Notes:
    The class automatically detects:
    
    - Number of levels for each factor
    - Upper and lower bounds for continuous factors
    - Decimal precision for continuous factors
    - Unique levels for categorical factors
    - Number of center points in the design

    The correct workflow is:
    
    - Initialize ImportDesign with file path and variable information
    - Export the experiments with `export_experiments()`, defining the response variables
    - Import the results with `import_results()` and proceed with analysis, visualization, and optimization

  """
  
  def __init__(self,
               vars : list[str],
               vars_type : list[str],
               file_path : str,
               coded : bool = False):

    super().__init__()
    
    # --------------------------- INPUT CHECK -------------------------------- #
    if len(vars_type) != len(vars):
        raise ValueError(f"Number of variables and variable types must be equal, please specify all ({vars})")
    for type in vars_type: 
      if type not in ["cont", "cat"]:
        raise ValueError(f"Variable types must be either 'cont' or 'cat', got {type!r}")
      
    # ------------------------- FILE UPLOADER -------------------------------- #
    df = self.upload_file(file_path)
    columns = df.columns
    
    # --------------------- DESIGN INITIALIZATION ---------------------------- #
    self._factors = {}
    for i, var in enumerate(vars):
      if var not in columns:
        raise ValueError(f"Variable '{var!r}' not found in the file columns: {list(columns)}")
      dec = df[var].apply(lambda x: str(x).split(".")[1] if "." in str(x) else "0").map(len).max()
      if vars_type[i]:
        if vars_type[i] == "cont":
          self._factors[var] = ContinuousFactor(
              n_levels = len(np.sort(df[var].unique())),
              lower_bound = float(np.min(df[var])),
              upper_bound = float(np.max(df[var])),
              decimals = dec
          )
        else:
          self._factors[var] = CategoricalFactor(
              levels = list(map(str, np.sort(df[var].unique())))
          )
    if coded:
      self._coded_design_matrix = df[vars].copy()
      self._design_matrix = df[vars].copy()
      
    else:   
      self._design_matrix = df[vars].copy()
      self._coded_design_matrix = self._code_matrix(self._design_matrix)
      
    self._design_type = "Generic"
    self._number_of_center_points(self._coded_design_matrix)

  def build_design_matrix(self):
    """
    Raise NotImplementedError for imported designs.
    
    """
    return NotImplementedError("This design cannot be modified")
